# Generated by Django 4.1.2 on 2022-10-30 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='pais',
        ),
    ]
